### ISSUE TITLE
How to use other picture formats

### ISSUE THREAD

**Issue by denalon** [nmasse-itix/photo-stream#1]
How to use other picture formats such as png gif？

**Comment by nmasse-itix** [comment]
Hi @denalon !

You can try this syntax in the frontmatter of your markdown file.

```md
---
date: "2000-01-01"
title: TODO
sort_by: "Name"
resources:
- src: '**.png'
---
```

However, given I'm using the Exif tags in various places of the theme, there is no warranty it will work with other formats. 

Hope it helps !
